### PR TITLE
Adding CIS tests for controls 4.08 and 4.09

### PR DESCRIPTION
**Pull request by ggsood**
Adding CIS tests for controls 4.08 and 4.09

### CODE REVIEW

**Comment by ggsood** [comment]
@googlebot I signed it!

**Comment by ggsood** [comment]
Will reopen need to test more use cases.

**Comment by dinvlad** [comment]
Any updates on this one?

**Comment by KonradSchieban** [comment]
Opened issue https://github.com/GoogleCloudPlatform/inspec-gcp-cis-benchmark/issues/79 for missing scored controls. Need to do an analysis how these should be implemented.

**Pull request closed without merging**
